import { useEffect, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { useForm } from 'react-hook-form';
import toast from 'react-hot-toast';
import { Button } from '../../components/ui/Button.jsx';
import { Card } from '../../components/ui/Card.jsx';
import { DataTable } from '../../components/ui/DataTable.jsx';
import { Input } from '../../components/ui/Input.jsx';
import { Loader } from '../../components/ui/Loader.jsx';
import { businessApi } from '../../services/businessApi.js';
import { useApiResource } from '../../hooks/useApiResource.js';
import { QueueEntriesTable } from './QueuePages.jsx';

export function OrganizationOnboardingPage() { const { register, handleSubmit, formState: { errors, isSubmitting } } = useForm(); const navigate = useNavigate(); return <Card><h2 className="text-2xl font-black">Create Organization</h2><p className="mt-2 text-sm text-slate-500">Set up the organization your queues belong to.</p><form className="mt-6 grid gap-4 md:max-w-xl" onSubmit={handleSubmit(async (values) => { const result = await businessApi.createOrganization(values); const org = result.data || result; toast.success('Organization created'); navigate(`/dashboard/organizations/${org._id || org.id}`); })}><Input label="Organization Name" {...register('name', { required: 'Organization name is required' })} error={errors.name?.message}/><Input label="Description" {...register('description')} /><Button disabled={isSubmitting}>Create Organization</Button></form></Card>; }

export function OrganizationListPage() { const { data, loading, error } = useApiResource(() => businessApi.listOrganizations(), []); if (loading) return <Loader />; const organizations = data?.items || data || []; return <Card><div className="flex items-center justify-between gap-4"><div><h2 className="text-2xl font-black">Organizations</h2><p className="text-sm text-slate-500">Choose an organization dashboard or create one.</p></div><Link to="/dashboard/organizations/new"><Button>Create Organization</Button></Link></div>{error && <p className="mt-4 text-sm text-rose-600">{error}</p>}<div className="mt-6"><DataTable columns={[{ key: 'name', header: 'Organization', render: (o) => <Link className="font-semibold text-indigo-600" to={`/dashboard/organizations/${o._id || o.id}`}>{o.name}</Link> }, { key: 'slug', header: 'Identifier' }, { key: 'status', header: 'Status' }]} rows={organizations} emptyTitle="No organizations yet" /></div></Card>; }

export function OrganizationDashboardPage() { const { organizationId } = useParams(); const { data, loading, reload } = useApiResource(() => businessApi.getOrganizationDashboard(organizationId), [organizationId]); const [calling, setCalling] = useState(false); useEffect(() => {}, []); if (loading) return <Loader />; const dashboard = data || {}; const organization = dashboard.organization || {}; const queues = dashboard.queues || []; const activeQueue = queues.find((q) => q.status === 'active') || queues[0]; return <div className="space-y-6"><Card><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="text-2xl font-black">{organization.name}</h2><p className="text-sm text-slate-500">Identifier: {organization.slug}</p></div><Link to="/dashboard/queues/new"><Button>Create Queue</Button></Link></div></Card><Card><h3 className="text-xl font-bold">Queues</h3><div className="mt-4"><DataTable columns={[{ key: 'name', header: 'Queue', render: (q) => <Link className="font-semibold text-indigo-600" to={`/dashboard/queues/${q._id || q.id}`}>{q.name}</Link> }, { key: 'status', header: 'Status' }, { key: 'identifier', header: 'Queue Identifier', render: (q) => q._id || q.id }, { key: 'length', header: 'Waiting', render: (q) => q.statistics?.currentQueueLength ?? 0 }]} rows={queues} emptyTitle="No queues yet" /></div></Card>{activeQueue && <><Card><div className="flex items-center justify-between"><h3 className="text-xl font-bold">Process {activeQueue.name}</h3><Button disabled={calling} onClick={async () => { setCalling(true); try { await businessApi.callNext(activeQueue._id || activeQueue.id); toast.success('Next customer called'); reload(); } finally { setCalling(false); } }}>Call Next</Button></div></Card><QueueEntriesTable queueId={activeQueue._id || activeQueue.id} /></>}</div>; }
