import { useEffect, useMemo, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { useDispatch, useSelector } from 'react-redux';
import toast from 'react-hot-toast';
import { useForm } from 'react-hook-form';
import { Badge } from '../../components/ui/Badge.jsx';
import { Button } from '../../components/ui/Button.jsx';
import { Card } from '../../components/ui/Card.jsx';
import { DataTable } from '../../components/ui/DataTable.jsx';
import { ErrorState } from '../../components/ui/ErrorState.jsx';
import { Input } from '../../components/ui/Input.jsx';
import { Loader } from '../../components/ui/Loader.jsx';
import { Select } from '../../components/ui/Select.jsx';
import { businessApi } from '../../services/businessApi.js';
import { useApiResource } from '../../hooks/useApiResource.js';
import { refreshSettled } from '../../store/realtimeSlice.js';

const statusOptions = ['draft', 'active', 'paused', 'closed', 'archived'].map((s) => ({ value: s, label: s }));
const entryStatuses = ['waiting', 'called', 'recalled', 'in_service', 'completed', 'skipped', 'cancelled', 'left'].map((s) => ({ value: s, label: s }));
const splitSort = (value) => { const [sortBy, sortOrder] = value.split(':'); return { sortBy, sortOrder }; };
export function QueueListPage({ mode = 'all' }) { const dispatch = useDispatch(); const { queues: liveQueues, lastEventAt } = useSelector((state) => state.realtime); const [query, setQuery] = useState({ page: 1, limit: 10, search: '', status: '', sort: 'createdAt:desc' }); const params = useMemo(() => ({ page: query.page, limit: query.limit, search: query.search || undefined, status: query.status || (mode === 'active' ? 'active' : undefined), ...splitSort(query.sort) }), [query, mode]); const { data, meta, loading, error, reload } = useApiResource(() => businessApi.listQueues(params), [params]); useEffect(() => { if (lastEventAt) reload().finally(() => dispatch(refreshSettled())); }, [lastEventAt, reload, dispatch]); const restQueues = data?.items || data || []; const queues = restQueues.map((q) => ({ ...q, ...(liveQueues[q._id || q.id] || {}) })); const columns = [{ key: 'name', header: 'Queue', render: (q) => <Link className="font-semibold text-indigo-600" to={`/dashboard/queues/${q._id || q.id}`}>{q.name}</Link> }, { key: 'status', header: 'Status', render: (q) => <Badge>{q.status}</Badge> }, { key: 'length', header: 'Length', render: (q) => q.statistics?.currentQueueLength ?? 0 }, { key: 'capacity', header: 'Capacity', render: (q) => q.maximumCapacity }, { key: 'actions', header: 'Actions', render: (q) => <Button variant="secondary" onClick={async () => { await businessApi.joinQueue(q._id || q.id); toast.success('Joined queue'); reload(); }}>Join Queue</Button> }]; return <Card><h2 className="text-2xl font-black">{mode === 'active' ? 'Active Queues' : 'Queue List'}</h2><div className="mt-6"><DataTable columns={columns} rows={queues} meta={meta} loading={loading} error={error} search={query.search} onSearch={(search) => setQuery({ ...query, search, page: 1 })} filters={[{ key: 'status', label: 'Status', value: query.status, options: statusOptions, onChange: (status) => setQuery({ ...query, status, page: 1 }) }]} sort={query.sort} onSort={(sort) => setQuery({ ...query, sort })} onPageChange={(page) => setQuery({ ...query, page })} emptyTitle="No queues found" /></div></Card>; }
export function QueueDetailsPage() { const { queueId } = useParams(); const liveQueue = useSelector((state) => state.realtime.queues[queueId]); const lastEventAt = useSelector((state) => state.realtime.lastEventAt); const { data, loading, error, reload } = useApiResource(() => businessApi.getQueue(queueId), [queueId]); useEffect(() => { if (lastEventAt) reload(); }, [lastEventAt, reload]); const queue = { ...(data || {}), ...(liveQueue || {}) }; if (loading && !queue.name) return <Loader />; if (error) return <ErrorState message={error} />; return <div className="space-y-6"><Card><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-2xl font-black">{queue.name}</h2><p className="text-slate-500">{queue.description || 'No description provided.'}</p></div><Badge>{queue.status}</Badge></div><div className="mt-6 grid gap-4 sm:grid-cols-3"><p><b>Token Prefix:</b> {queue.tokenPrefix}</p><p><b>Capacity:</b> {queue.maximumCapacity}</p><p><b>Avg Service:</b> {queue.averageServiceTimeMinutes} min</p></div><div className="mt-6 flex flex-wrap gap-2">{['activate','pause','resume','close','archive'].map((action) => <Button key={action} variant="secondary" onClick={async () => { await businessApi.transitionQueue(queueId, action); toast.success(`Queue ${action} requested`); reload(); }}>{action}</Button>)}</div></Card><QueueEntriesTable queueId={queueId} /></div>; }
export function QueueEntriesTable({ queueId, history = false }) { const dispatch = useDispatch(); const { entries: liveEntries, lastEventAt } = useSelector((state) => state.realtime); const [query, setQuery] = useState({ page: 1, search: '', status: history ? 'completed' : '', sort: 'joinedAt:asc' }); const params = useMemo(() => ({ queueId, page: query.page, limit: 10, search: query.search || undefined, status: query.status || undefined, ...splitSort(query.sort) }), [query, queueId]); const { data, meta, loading, error, reload } = useApiResource(() => businessApi.listEntries(params), [params]); useEffect(() => { if (lastEventAt) reload().finally(() => dispatch(refreshSettled())); }, [lastEventAt, reload, dispatch]); const restEntries = data?.items || data || []; const entries = restEntries.map((e) => ({ ...e, ...(liveEntries[e._id || e.id] || {}) })).concat(Object.values(liveEntries).filter((e) => (!queueId || e.queueId === queueId) && !restEntries.some((r) => (r._id || r.id) === (e._id || e.id)))); const columns = [{ key: 'token', header: 'Token' }, { key: 'status', header: 'Status', render: (e) => <Badge>{e.status}</Badge> }, { key: 'position', header: 'Position' }, { key: 'estimatedWaitMinutes', header: 'Wait' }, { key: 'actions', header: 'Actions', render: (e) => <div className="flex flex-wrap gap-2"><Link className="text-sm font-semibold text-indigo-600" to={`/dashboard/entries/${e._id || e.id}`}>Details</Link><button onClick={async()=>{await businessApi.leaveEntry(e._id || e.id); toast.success('Left queue'); reload();}}>Leave</button><button onClick={async()=>{await businessApi.recallEntry(e._id || e.id); reload();}}>Recall</button><button onClick={async()=>{await businessApi.skipEntry(e._id || e.id); reload();}}>Skip</button><button onClick={async()=>{await businessApi.completeEntry(e._id || e.id); reload();}}>Complete</button></div> }]; return <Card><h3 className="text-xl font-bold">{history ? 'Queue History' : 'Current Queue'}</h3><div className="mt-4"><DataTable columns={columns} rows={entries} meta={meta} loading={loading} error={error} search={query.search} onSearch={(search) => setQuery({ ...query, search, page: 1 })} filters={[{ key: 'status', label: 'Status', value: query.status, options: entryStatuses, onChange: (status) => setQuery({ ...query, status, page: 1 }) }]} sort={query.sort} onSort={(sort) => setQuery({ ...query, sort })} onPageChange={(page) => setQuery({ ...query, page })} emptyTitle="No queue entries" /></div></Card>; }
export function JoinQueuePage() { const { register, handleSubmit, formState: { errors, isSubmitting } } = useForm(); const [joined, setJoined] = useState(null); return <Card><h2 className="text-2xl font-black">Join Queue</h2><form className="mt-6 grid gap-4 md:max-w-xl" onSubmit={handleSubmit(async (values) => { const result = await businessApi.joinQueue(values.queueId, { metadata: { note: values.note } }); setJoined(result?.data || result); toast.success('Joined queue'); })}><Input label="Queue ID" {...register('queueId', { required: 'Queue ID is required' })} error={errors.queueId?.message}/><Input label="Note" {...register('note')} /><Button disabled={isSubmitting}>Join Queue</Button></form>{joined && <div className="mt-6 grid gap-3 rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm dark:border-emerald-900 dark:bg-emerald-950/30"><h3 className="text-lg font-bold">Joined {joined.queueName || 'Queue'}</h3><p><b>Token Number:</b> {joined.token || joined.tokenNumber}</p><p><b>Queue Position:</b> {joined.position}</p><p><b>Queue Status:</b> {joined.queueStatus || joined.status}</p>{joined.estimatedWaitMinutes != null && <p><b>Estimated Waiting Time:</b> {joined.estimatedWaitMinutes} min</p>}</div>}</Card>; }
export function QueueHistoryPage() { return <QueueEntriesTable history />; }
export function EntryDetailsPage() { const { entryId } = useParams(); const { data, loading, error, reload } = useApiResource(() => businessApi.getEntry(entryId), [entryId]); if (loading) return <Loader />; if (error) return <ErrorState message={error} />; return <Card><h2 className="text-2xl font-black">Queue Entry Details</h2><pre className="mt-4 overflow-auto rounded-xl bg-slate-100 p-4 text-sm dark:bg-slate-800">{JSON.stringify(data, null, 2)}</pre><div className="mt-4 flex gap-2"><Button variant="secondary" onClick={async()=>{await businessApi.leaveEntry(entryId); reload();}}>Leave Queue</Button><Button onClick={async()=>{await businessApi.completeEntry(entryId); reload();}}>Complete Service</Button></div></Card>; }
export function CurrentQueuePage() { return <QueueEntriesTable />; }
