const { User, Session, AuthToken } = require('../models');
const { ConflictError, AuthenticationError, ValidationError, NotFoundError } = require('../errors');
const { hash, randomToken, signAccessToken, refreshExpiresAt } = require('./tokenService');
const passwords = require('./passwordService');
const audit = require('./auditService');
const normalizeEmail = (email) => String(email || '').trim().toLowerCase();
const publicUser = (u) => u.toJSON ? u.toJSON() : u;
async function createSession(user, req) { const refreshToken = randomToken(); const session = await Session.create({ user: user._id, refreshTokenHash: hash(refreshToken), tokenFamily: randomToken(), expiresAt: refreshExpiresAt(), ip: req?.ip, userAgent: req?.get?.('user-agent') }); return { accessToken: signAccessToken(user), refreshToken, session }; }
async function issueAuthToken(user, type, minutes = 60) { const token = randomToken(); await AuthToken.create({ user: user._id, type, tokenHash: hash(token), expiresAt: new Date(Date.now() + minutes * 60000) }); return token; }
async function register(input, req) { const email = normalizeEmail(input.email); if (await User.findOne({ email })) throw new ConflictError('Email already registered'); passwords.assertStrong(input.password); const passwordHash = await passwords.hashPassword(input.password); const user = await User.create({ email, name: input.name, passwordHash, passwordHistory: [{ hash: passwordHash }], roleNames: ['user'], passwordChangedAt: new Date() }); const verificationToken = await issueAuthToken(user, 'email_verification', 1440); await audit.record('auth.registered', { actor: user._id, req }); return { user: publicUser(user), verificationToken }; }
async function login({ email, password }, req) { const user = await User.findOne({ email: normalizeEmail(email) }).select('+passwordHash'); if (!user || !(await passwords.verifyPassword(password, user.passwordHash))) throw new AuthenticationError('Invalid credentials'); if (user.status !== 'active') throw new AuthenticationError('Account is not active'); const sessionData = await createSession(user, req); user.lastLoginAt = new Date(); user.loginHistory.push({ at: user.lastLoginAt, ip: req?.ip, userAgent: req?.get?.('user-agent') }); await user.save(); await audit.record('auth.login', { actor: user._id, req }); return { user: publicUser(user), ...sessionData }; }
async function rotateRefreshToken(token, req) { const tokenHash = hash(token || ''); const session = await Session.findOne({ refreshTokenHash: tokenHash }).populate('user'); if (!session || session.revokedAt || session.expiresAt <= new Date() || session.user?.status !== 'active') { if (session) await Session.updateMany({ tokenFamily: session.tokenFamily, revokedAt: null }, { revokedAt: new Date(), revokedReason: 'refresh_reuse' }); throw new AuthenticationError('Invalid or expired refresh token'); } const newRefresh = randomToken(); session.refreshTokenHash = hash(newRefresh); session.lastActivityAt = new Date(); session.ip = req?.ip || session.ip; await session.save(); return { accessToken: signAccessToken(session.user), refreshToken: newRefresh, session, user: publicUser(session.user) }; }
async function logout(token, userId, all, req) { const q = all ? { user: userId, revokedAt: null } : { refreshTokenHash: hash(token || ''), revokedAt: null }; await Session.updateMany(q, { revokedAt: new Date(), revokedReason: 'logout' }); await audit.record(all ? 'auth.logout_all' : 'auth.logout', { actor: userId, req }); }
async function forgotPassword(email, req) { const user = await User.findOne({ email: normalizeEmail(email) }); if (!user) return { sent: true }; const resetToken = await issueAuthToken(user, 'password_reset', 60); await audit.record('auth.password_reset_requested', { actor: user._id, req }); return { sent: true, resetToken }; }
async function resetPassword(token, password, req) { passwords.assertStrong(password); const authToken = await AuthToken.findOne({ tokenHash: hash(token || ''), type: 'password_reset', usedAt: null }).populate('user'); if (!authToken || authToken.expiresAt <= new Date()) throw new ValidationError('Invalid or expired password reset token'); const user = await User.findById(authToken.user._id).select('+passwordHash +passwordHistory'); await passwords.assertNotReused(password, user.passwordHistory); const passwordHash = await passwords.hashPassword(password); user.passwordHash = passwordHash; user.passwordHistory.push({ hash: passwordHash }); user.passwordChangedAt = new Date(); await user.save(); authToken.usedAt = new Date(); await authToken.save(); await Session.updateMany({ user: user._id, revokedAt: null }, { revokedAt: new Date(), revokedReason: 'password_reset' }); await audit.record('auth.password_reset', { actor: user._id, req }); }
async function changePassword(userId, currentPassword, nextPassword, req) { const user = await User.findById(userId).select('+passwordHash +passwordHistory'); if (!user) throw new NotFoundError('User not found'); if (!(await passwords.verifyPassword(currentPassword, user.passwordHash))) throw new AuthenticationError('Invalid credentials'); return resetPassword(await issueAuthToken(user, 'password_reset', 5), nextPassword, req); }
async function verifyEmail(token, req) { const authToken = await AuthToken.findOne({ tokenHash: hash(token || ''), type: 'email_verification', usedAt: null }).populate('user'); if (!authToken || authToken.expiresAt <= new Date()) throw new ValidationError('Invalid or expired verification token'); authToken.user.emailVerified = true; authToken.user.emailVerifiedAt = new Date(); authToken.usedAt = new Date(); await authToken.user.save(); await authToken.save(); await audit.record('auth.email_verified', { actor: authToken.user._id, req }); return publicUser(authToken.user); }
async function googleLogin({ idToken, email, name, googleId }, req) { if (idToken && !email) { const r = await fetch(`https://oauth2.googleapis.com/tokeninfo?id_token=${idToken}`); if (!r.ok) throw new AuthenticationError('Invalid Google token'); const p = await r.json(); email = p.email; name = p.name; googleId = p.sub; } let user = await User.findOne({ $or: [{ email: normalizeEmail(email) }, { googleId }] }); if (!user) user = await User.create({ email: normalizeEmail(email), name: name || email, googleId, emailVerified: true, emailVerifiedAt: new Date(), roleNames: ['user'] }); else if (!user.googleId) { user.googleId = googleId; await user.save(); } const sessionData = await createSession(user, req); await audit.record('auth.google_login', { actor: user._id, req }); return { user: publicUser(user), ...sessionData }; }
module.exports = { register, login, rotateRefreshToken, logout, forgotPassword, resetPassword, changePassword, verifyEmail, issueAuthToken, googleLogin };
