const express = require('express');
const path = require('path');
const helmet = require('helmet');
const cors = require('cors');
const compression = require('compression');
const cookieParser = require('cookie-parser');
const swaggerUi = require('swagger-ui-express');
const { config } = require('./config/env');
const routes = require('./routes');
const requestId = require('./middlewares/requestId');
const httpLogger = require('./middlewares/httpLogger');
const { apiLimiter, sanitizeRequest, preventParameterPollution } = require('./middlewares/security');
const { notFoundHandler, errorHandler } = require('./middlewares/errorHandler');
const { loadOpenApiSpec } = require('./config/swagger');

const app = express();
app.set('trust proxy', config.app.trustProxy);
app.use(requestId);
app.use(helmet());
app.use(cors({ origin: config.cors.origin === '*' ? true : config.cors.origin.split(','), credentials: config.cors.credentials }));
app.use(compression());
app.use(cookieParser());
app.use(express.json({ limit: '1mb' }));
app.use(express.urlencoded({ extended: true, limit: '1mb' }));
app.use(sanitizeRequest);
app.use(preventParameterPollution);
app.use(httpLogger);
app.use('/public', express.static(path.resolve(__dirname, '../public')));
app.use(`${config.app.apiPrefix}/${config.app.apiVersion}/docs`, swaggerUi.serve, swaggerUi.setup(loadOpenApiSpec()));
app.use(`${config.app.apiPrefix}/${config.app.apiVersion}`, apiLimiter, routes);
app.use(notFoundHandler);
app.use(errorHandler);
module.exports = app;
