const express = require('express');
const healthRoutes = require('./healthRoutes');
const authRoutes = require('./authRoutes');
const rbacRoutes = require('./rbacRoutes');
const queueRoutes = require('./queueRoutes');
const queueEntryRoutes = require('./queueEntryRoutes');
const notificationRoutes = require('./notificationRoutes');
const router = express.Router();
router.use('/', healthRoutes);
router.use('/auth', authRoutes);
router.use('/rbac', rbacRoutes);
router.use('/queues', queueRoutes);
router.use('/queue-entries', queueEntryRoutes);
router.use('/notifications', notificationRoutes);
module.exports = router;
