const express = require('express');
const healthRoutes = require('./healthRoutes');
const authRoutes = require('./authRoutes');
const rbacRoutes = require('./rbacRoutes');
const queueRoutes = require('./queueRoutes');
const router = express.Router();
router.use('/', healthRoutes);
router.use('/auth', authRoutes);
router.use('/rbac', rbacRoutes);
router.use('/queues', queueRoutes);
module.exports = router;
