import { Link, NavLink, Outlet, useLocation } from 'react-router-dom';
import { useDispatch, useSelector } from 'react-redux';
import { logout } from '../features/auth/authSlice.js';
import { Avatar } from '../components/ui/Avatar.jsx';
import { ThemeToggle } from '../components/ThemeToggle.jsx';
import { NotificationCenter } from '../components/notifications/NotificationCenter.jsx';

const navByRole = {
  customer: [['/dashboard','Dashboard'],['/dashboard/queues','Join Queue'],['/dashboard/queues/active','Active Queue'],['/dashboard/queues/history','Queue History'],['/dashboard/analytics','Analytics'],['/dashboard/profile','Profile'],['/dashboard/settings','Account Settings']],
  user: [['/dashboard','Dashboard'],['/dashboard/queues','Join Queue'],['/dashboard/queues/active','Active Queue'],['/dashboard/queues/history','Queue History'],['/dashboard/analytics','Analytics'],['/dashboard/profile','Profile'],['/dashboard/settings','Account Settings']],
  counter_operator: [['/dashboard','Counter Dashboard'],['/dashboard/queues/current','Current Queue'],['/dashboard/queues','Call Next'],['/dashboard/queues/status','Queue Status'],['/dashboard/analytics','Analytics'],['/dashboard/profile','Profile']],
  venue_manager: [['/dashboard','Dashboard'],['/dashboard/queues','Queue Management'],['/dashboard/counters','Counter Management'],['/dashboard/employees','Employee Management'],['/dashboard/analytics','Analytics'],['/dashboard/profile','Profile']],
  organization_admin: [['/dashboard','Dashboard'],['/dashboard/branches','Branch Management'],['/dashboard/venues','Venue Management'],['/dashboard/users','User Management'],['/dashboard/roles','Role Management'],['/dashboard/queues','Queue Management'],['/dashboard/analytics','Analytics']],
  super_admin: [['/dashboard','Dashboard'],['/dashboard/branches','Branch Management'],['/dashboard/venues','Venue Management'],['/dashboard/users','User Management'],['/dashboard/roles','Role Management'],['/dashboard/queues','Queue Management'],['/dashboard/analytics','Analytics']],
};
export default function DashboardLayout(){const {user}=useSelector(s=>s.auth);const {connected=false,reconnecting=false,refreshing=false}=useSelector(s=>s.realtime||{});const dispatch=useDispatch();const crumbs=useLocation().pathname.split('/').filter(Boolean);const role=user?.role||'customer';const nav=navByRole[role]||navByRole.organization_admin;return <div className="min-h-screen bg-slate-50 text-slate-950 dark:bg-slate-950 dark:text-white md:flex"><aside className="border-b bg-white p-4 dark:border-slate-800 dark:bg-slate-900 md:min-h-screen md:w-64 md:border-r"><Link to="/dashboard" className="text-xl font-black">QueueIt</Link><nav className="mt-8 grid gap-2">{nav.map(([to,label])=><NavLink key={`${to}-${label}`} to={to} end={to==='/dashboard'} className={({isActive})=>`rounded-xl px-3 py-2 text-sm font-medium transition ${isActive?'bg-slate-950 text-white dark:bg-white dark:text-slate-950':'hover:bg-slate-100 dark:hover:bg-slate-800'}`}>{label}</NavLink>)}</nav>{user?.role&&<p className="mt-6 text-xs uppercase tracking-wide text-slate-500">Role: {user.role}</p>}</aside><section className="flex-1"><header className="sticky top-0 z-10 flex items-center justify-between border-b bg-white/80 px-6 py-4 backdrop-blur dark:border-slate-800 dark:bg-slate-950/80"><div><p className="text-xs text-slate-500">/{crumbs.join(' / ')}</p><h1 className="font-semibold">Workspace</h1></div><div className="flex items-center gap-3"><span className={`rounded-full px-2 py-1 text-xs font-bold ${connected?'bg-emerald-100 text-emerald-700':'bg-amber-100 text-amber-700'}`} role="status" aria-live="polite">{connected?'Live':reconnecting?'Reconnecting':'Offline'}</span>{refreshing&&<span className="text-xs text-slate-500">Syncing…</span>}<NotificationCenter/><ThemeToggle/><Avatar name={user?.name||user?.email}/><button onClick={()=>dispatch(logout())} className="text-sm font-semibold">Logout</button></div></header><main className="p-6"><Outlet/></main></section></div>}
