import { useForm } from 'react-hook-form';
import { useSelector } from 'react-redux';
import { Button } from '../components/ui/Button.jsx';
import { Card } from '../components/ui/Card.jsx';
import { Input } from '../components/ui/Input.jsx';
import { Select } from '../components/ui/Select.jsx';
import { emailRules, passwordRules } from '../utils/validation.js';

export default function ProfilePage(){const {user}=useSelector(s=>s.auth);const {register,handleSubmit,formState:{errors,isSubmitting}}=useForm({defaultValues:{name:user?.name||'',email:user?.email||''}});const passwordForm=useForm();return <div className="grid gap-6 xl:grid-cols-2"><Card><h2 className="text-2xl font-bold">View Profile</h2><div className="mt-4 flex items-center gap-4"><label className="grid size-20 cursor-pointer place-items-center rounded-full bg-slate-100 text-2xl font-black dark:bg-slate-800">{(user?.name||user?.email||'U').slice(0,1).toUpperCase()}<input type="file" accept="image/*" className="sr-only" /></label><div><p className="font-semibold">{user?.name||'QueueIt User'}</p><p className="text-sm text-slate-500">{user?.email}</p><p className="text-xs uppercase text-slate-400">{user?.role}</p></div></div></Card><Card><h2 className="text-2xl font-bold">Edit Profile</h2><form className="mt-4 grid gap-4" onSubmit={handleSubmit(()=>{})}><Input label="Name" {...register('name',{required:'Name is required'})} error={errors.name?.message}/><Input label="Email" type="email" {...register('email',emailRules)} error={errors.email?.message}/><Button disabled={isSubmitting}>Save Profile</Button></form></Card><Card><h2 className="text-2xl font-bold">Change Password</h2><form className="mt-4 grid gap-4" onSubmit={passwordForm.handleSubmit(()=>{})}><Input label="Current Password" type="password" {...passwordForm.register('currentPassword',{required:'Current password is required'})} error={passwordForm.formState.errors.currentPassword?.message}/><Input label="New Password" type="password" {...passwordForm.register('password',passwordRules)} error={passwordForm.formState.errors.password?.message}/><Button>Change Password</Button></form></Card><Card><h2 className="text-2xl font-bold">Theme Settings</h2><div className="mt-4"><Select label="Theme"><option>Use header theme toggle</option><option>Light</option><option>Dark</option></Select></div><h3 className="mt-6 font-bold">Account Settings</h3><p className="mt-2 text-sm text-slate-500">Security, profile, and avatar controls are grouped here for Phase 9B.</p></Card></div>}
